### PR TITLE
Add new format type, migrate to Dart 2.12

### PR DESCRIPTION
**Pull request by l7ssha**
I've talked about that feature in #11. This PR adds new option to format function for generating string in format like `14 days, 4 hours, 55 minutes, 6 seconds`.

I added support for Dart 2.12 - its around corner and I thought that I will do that in this PR.

TODO: 
 - [x] Add support for seconds
       Currently lib doesn't have support for seconds - should I add seconds in this PR?
 - [x] Add support for years
 - [x] Update changelog, readme, docs and examples
 - [x] Update arabic language and verify turkish

Is API looking good or should this feature be in its own separate function or maybe class?

### CODE REVIEW

**Comment by baderouaich** [comment]
Hi @l7ssha, thank you for contributing!
- **Upgrading to Dart 2.12**
this version of dart has some cool features like null safety..etc, but we should keep in mind flutter developers who have dartlang integrated with flutter sdk which is so far version 2.10. i think we stick with this version for now.

- **API**
as i said dart 2.12 with its cool features will result in a cleaner code as you have written. without that i guess we just have to do it the classic way until flutter upgrades the integrated dart sdk in the stable channel.
the couple functions of short and long form format are ok since we don't have much code in them.

- **Format** 
i think we can have two functions, format which is the default, and formatFull which allows the user to select which units to format. can be something like :
```
String formatFull(DateTime date,
    {String locale = 'en',
    DateTime clock,
    bool years = false,
    bool days = true,
    bool hours = true,
    bool minutes = true,
    bool seconds = true}) {
  final language = _languages[locale] ?? English();
  final duration = clock.difference(date);
  final buffer = StringBuffer();

  if (days) {
    buffer.write(language.days(duration.inDays));
    buffer.write(', ');
  }
  if (hours) {
    buffer.write(language.hours(duration.inHours % 24));
    buffer.write(', ');
  }
 .
 .
 .

  return buffer.toString();
}
```

let me know what you think. thank you!

**Comment by l7ssha** [comment]
About upgrade with Dart 2.12 - I was thinking about merging this PR with same time as release of Dart 2.12 - so as you said flutter and other project will catch up with adapting. 

Rest of comments looks good for me - I will fix the code according to them.
Thanks for you time!

**Comment by l7ssha** [comment]
I've decided to not include flag for displaying all constraints separately (`bool years = false, bool days = true, bool hours = true`) because it would add too much complexity. I've added two more test to cover more cases and Arabic needs to be updated, and Turkish verified if everything all right.

**Comment by baderouaich** [comment]
Hi @l7ssha! thank you for adding the seconds unit! 
i will implement the Arabic translation.
meanwhile @bgoktugozdemir, can you verify the Turkish translation of the latest modifications in this PR?
Thank you guys!

**Comment by bgoktugozdemir** [comment]
@BaderEddineOuaich I didn't see any problem on the _files changed_ tab.

**Comment by baderouaich** [comment]
Perfect! time to merge and implement Arabic, and then publish to pub.dev
once again, Thanks @l7ssha Teşekkürler @bgoktugozdemir

**Comment by bgoktugozdemir** [comment]
You are welcome :) @BaderEddineOuaich

**Pull request merged**
